package com.a105.zani.common.error;

public enum ErrorType {
    BAD_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    PAYLOAD_TOO_LARGE,
    UNSUPPORTED_MEDIA_TYPE,
    SERVICE_UNAVAILABLE,
    INTERNAL_SERVER_ERROR
}
