/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google 계정으로 로그인
         * @description 프론트에서 Google Identity Services로 발급받은 ID Token을 검증하고,
         *     최초 로그인이면 회원을 생성한 뒤 자체 access/refresh 토큰을 발급한다.
         *     refresh 토큰은 응답 바디가 아닌 HttpOnly 쿠키(auth/refresh 경로)로 내려간다.
         */
        post: operations["loginWithGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내가 참여 중인 세션 목록 조회 */
        get: operations["listSessions"];
        put?: never;
        /**
         * 세션(강의방) 생성
         * @description 진행 중인 방이 없는 강사가 제목과 함께 세션을 생성한다.
         *     LIVE 상태로 즉시 시작되며, 고유 초대 코드가 함께 발급된다.
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 초대 코드로 세션 입장
         * @description 유효한 초대 코드로 입장하면 STUDENT 멤버십을 즉시 얻는다.
         *     이미 참여 중인 세션이면 멱등하게 기존 멤버십을 반환한다.
         */
        post: operations["joinSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GoogleLoginRequest: {
            idToken: string;
        };
        GoogleLoginResponse: {
            accessToken?: string;
            /** Format: date-time */
            accessTokenExpiresAt?: string;
            email?: string;
            displayName?: string;
            profileImageUrl?: string | null;
            newMember?: boolean;
        };
        GoogleLoginApiResponse: {
            isSuccess: boolean;
            code?: string;
            message?: string;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
            data?: components["schemas"]["GoogleLoginResponse"];
        };
        /** @enum {string} */
        SessionStatus: "LIVE" | "ENDED";
        /** @enum {string} */
        SessionRole: "INSTRUCTOR" | "STUDENT";
        ApiResponse: {
            isSuccess: boolean;
            code?: string;
            message?: string;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
            data?: unknown;
        };
        CreateSessionRequest: {
            title: string;
        };
        CreateSessionResponse: {
            /** Format: int64 */
            sessionId?: number;
            inviteCode?: string;
            status?: components["schemas"]["SessionStatus"];
            role?: components["schemas"]["SessionRole"];
            /** Format: date-time */
            expiresAt?: string;
        };
        CreateSessionApiResponse: {
            isSuccess: boolean;
            code?: string;
            message?: string;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
            data?: components["schemas"]["CreateSessionResponse"];
        };
        JoinSessionRequest: {
            inviteCode: string;
        };
        JoinSessionResponse: {
            /** Format: int64 */
            sessionId?: number;
            inviteCode?: string;
            status?: components["schemas"]["SessionStatus"];
            role?: components["schemas"]["SessionRole"];
        };
        JoinSessionApiResponse: {
            isSuccess: boolean;
            code?: string;
            message?: string;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
            data?: components["schemas"]["JoinSessionResponse"];
        };
        SessionSummary: {
            /** Format: int64 */
            sessionId?: number;
            inviteCode?: string;
            status?: components["schemas"]["SessionStatus"];
            role?: components["schemas"]["SessionRole"];
        };
        SessionListApiResponse: {
            isSuccess: boolean;
            code?: string;
            message?: string;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
            data?: components["schemas"]["SessionSummary"][];
        };
    };
    responses: {
        /** @description 인증되지 않음 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "isSuccess": false,
                 *       "code": "COMM_401",
                 *       "message": "Authentication is required"
                 *     }
                 */
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    loginWithGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequest"];
            };
        };
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleLoginApiResponse"];
                };
            };
            /** @description 요청 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Google ID Token이 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "isSuccess": false,
                     *       "code": "AUTH_008",
                     *       "message": "Google ID token is invalid"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 세션 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description 세션 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 이미 진행 중인 세션이 있음 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "isSuccess": false,
                     *       "code": "SESSION_APP_001",
                     *       "message": "An active session already exists"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    joinSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinSessionRequest"];
            };
        };
        responses: {
            /** @description 세션 입장 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinSessionApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 유효하지 않은 초대 코드 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "isSuccess": false,
                     *       "code": "SESSION_APP_005",
                     *       "message": "No session found for the given invite code"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
}
